require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RiversController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # River. As you add validations to River, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RiversController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rivers as @rivers" do
      river = River.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rivers)).to eq([river])
    end
  end

  describe "GET #show" do
    it "assigns the requested river as @river" do
      river = River.create! valid_attributes
      get :show, {:id => river.to_param}, valid_session
      expect(assigns(:river)).to eq(river)
    end
  end

  describe "GET #new" do
    it "assigns a new river as @river" do
      get :new, {}, valid_session
      expect(assigns(:river)).to be_a_new(River)
    end
  end

  describe "GET #edit" do
    it "assigns the requested river as @river" do
      river = River.create! valid_attributes
      get :edit, {:id => river.to_param}, valid_session
      expect(assigns(:river)).to eq(river)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new River" do
        expect {
          post :create, {:river => valid_attributes}, valid_session
        }.to change(River, :count).by(1)
      end

      it "assigns a newly created river as @river" do
        post :create, {:river => valid_attributes}, valid_session
        expect(assigns(:river)).to be_a(River)
        expect(assigns(:river)).to be_persisted
      end

      it "redirects to the created river" do
        post :create, {:river => valid_attributes}, valid_session
        expect(response).to redirect_to(River.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved river as @river" do
        post :create, {:river => invalid_attributes}, valid_session
        expect(assigns(:river)).to be_a_new(River)
      end

      it "re-renders the 'new' template" do
        post :create, {:river => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested river" do
        river = River.create! valid_attributes
        put :update, {:id => river.to_param, :river => new_attributes}, valid_session
        river.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested river as @river" do
        river = River.create! valid_attributes
        put :update, {:id => river.to_param, :river => valid_attributes}, valid_session
        expect(assigns(:river)).to eq(river)
      end

      it "redirects to the river" do
        river = River.create! valid_attributes
        put :update, {:id => river.to_param, :river => valid_attributes}, valid_session
        expect(response).to redirect_to(river)
      end
    end

    context "with invalid params" do
      it "assigns the river as @river" do
        river = River.create! valid_attributes
        put :update, {:id => river.to_param, :river => invalid_attributes}, valid_session
        expect(assigns(:river)).to eq(river)
      end

      it "re-renders the 'edit' template" do
        river = River.create! valid_attributes
        put :update, {:id => river.to_param, :river => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested river" do
      river = River.create! valid_attributes
      expect {
        delete :destroy, {:id => river.to_param}, valid_session
      }.to change(River, :count).by(-1)
    end

    it "redirects to the rivers list" do
      river = River.create! valid_attributes
      delete :destroy, {:id => river.to_param}, valid_session
      expect(response).to redirect_to(rivers_url)
    end
  end

end
